apiVersion: cdi.kubevirt.io/v1beta1
kind: DataImportCron
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
  name: datasource-centos-stream9-import-cron
spec:
  garbageCollect: Outdated
  importsToKeep: 3
  managedDataSource: datasource-centos-stream9
  schedule: 0 0 */5 * *
  template:
    metadata: {}
    spec:
      source:
        registry:
          url: 'docker://quay.io/containerdisks/centos-stream:9'
      storage:
        resources:
          requests:
            storage: 30Gi
    status: {}